-- Create X-Small Warehouse with AutoSuspend
CREATE OR REPLACE WAREHOUSE DEMO_WH
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- Create Database
CREATE OR REPLACE DATABASE DEMO_RETAIL;

-- Create Schemas
CREATE OR REPLACE SCHEMA DEMO_RETAIL.RAW;
CREATE OR REPLACE SCHEMA DEMO_RETAIL.STAGE;
CREATE OR REPLACE SCHEMA DEMO_RETAIL.CORE;
CREATE OR REPLACE SCHEMA DEMO_RETAIL.MART;