-- Define Reusable CSV File Format
CREATE OR REPLACE FILE FORMAT DEMO_RETAIL.RAW.CSV_FMT
    TYPE = 'CSV'
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    FIELD_DELIMITER = ','
    NULL_IF = ('', 'NULL')
    EMPTY_FIELD_AS_NULL = TRUE;

-- Define Internal Stage for RAW layer
CREATE OR REPLACE STAGE DEMO_RETAIL.RAW.RAW_STAGE
    FILE_FORMAT = DEMO_RETAIL.RAW.CSV_FMT;