// Copying CSVs into their corresponding RAW table

-- Customers Table
COPY INTO DEMO_RETAIL.RAW.CUSTOMERS
FROM @DEMO_RETAIL.RAW.RAW_STAGE/df_Customers.csv
FILE_FORMAT = (FORMAT_NAME = DEMO_RETAIL.RAW.CSV_FMT);

-- Orders Table
COPY INTO DEMO_RETAIL.RAW.ORDERS
FROM @DEMO_RETAIL.RAW.RAW_STAGE/df_Orders.csv
FILE_FORMAT = (FORMAT_NAME = DEMO_RETAIL.RAW.CSV_FMT);

-- Order Items Table
COPY INTO DEMO_RETAIL.RAW.ORDER_ITEMS
FROM @DEMO_RETAIL.RAW.RAW_STAGE/df_OrderItems.csv
FILE_FORMAT = (FORMAT_NAME = DEMO_RETAIL.RAW.CSV_FMT);

-- Products Table
COPY INTO DEMO_RETAIL.RAW.PRODUCTS
FROM @DEMO_RETAIL.RAW.RAW_STAGE/df_Products.csv
FILE_FORMAT = (FORMAT_NAME = DEMO_RETAIL.RAW.CSV_FMT);

-- Payments Table
COPY INTO DEMO_RETAIL.RAW.PAYMENTS
FROM @DEMO_RETAIL.RAW.RAW_STAGE/df_Payments.csv
FILE_FORMAT = (FORMAT_NAME = DEMO_RETAIL.RAW.CSV_FMT);